"""Local visual test. Serve the site first:  python3 -m http.server 8765
Optional admin test: run `npx decap-server` in this folder (port 8081)."""
import asyncio
from playwright.async_api import async_playwright
BASE = "http://localhost:8765"; OUT = "screenshots"
async def main():
    async with async_playwright() as p:
        b = await p.chromium.launch(executable_path="/usr/bin/google-chrome", args=["--no-sandbox"])
        errs = []
        d = await b.new_page(viewport={"width": 1440, "height": 900})
        d.on("pageerror", lambda e: errs.append(str(e)))
        d.on("console", lambda m: errs.append(m.text) if m.type == "error" else None)
        await d.goto(BASE + "/index.html"); await d.wait_for_timeout(3500)
        await d.screenshot(path=f"{OUT}/01-landing-desktop.png")
        await d.goto(BASE + "/portfolio.html"); await d.wait_for_timeout(1500)
        await d.screenshot(path=f"{OUT}/02-portfolio-top.png")
        await d.evaluate("window.scrollTo(0, document.querySelector('#work').offsetTop - 64)"); await d.wait_for_timeout(1500)
        await d.screenshot(path=f"{OUT}/03-portfolio-all.png")
        await d.click("[data-filter='residential']"); await d.wait_for_timeout(1500)
        await d.screenshot(path=f"{OUT}/04-residential-tab.png")
        await d.hover(".card__btn"); await d.wait_for_timeout(800)
        await d.screenshot(path=f"{OUT}/05-folder-card-hover.png")
        await d.click(".card__btn"); await d.wait_for_timeout(1500)
        await d.screenshot(path=f"{OUT}/06-folder-detail.png")
        await d.click("#lb-zoom"); await d.wait_for_timeout(1500)
        await d.screenshot(path=f"{OUT}/07-folder-detail-zoom.png")
        await d.keyboard.press("Escape"); await d.keyboard.press("Escape"); await d.wait_for_timeout(600)
        await d.click("[data-filter='mixed-use']"); await d.wait_for_timeout(1500)
        await d.screenshot(path=f"{OUT}/08-empty-category-mixed-use.png")
        await d.click("[data-filter='all']"); await d.wait_for_timeout(600)
        await d.evaluate("document.querySelector('#about').scrollIntoView()"); await d.wait_for_timeout(1000)
        await d.screenshot(path=f"{OUT}/09-about.png")
        await d.evaluate("window.scrollTo(0, document.body.scrollHeight)"); await d.wait_for_timeout(1000)
        await d.screenshot(path=f"{OUT}/10-contact.png")
        await d.evaluate("document.querySelectorAll('.card,.cat__head,.soon').forEach(e=>e.classList.add('is-in'))")
        await d.screenshot(path=f"{OUT}/11-portfolio-fullpage.png", full_page=True)
        m = await b.new_page(viewport={"width": 390, "height": 844}, device_scale_factor=2, is_mobile=True, has_touch=True)
        await m.goto(BASE + "/index.html"); await m.wait_for_timeout(3500)
        await m.screenshot(path=f"{OUT}/12-mobile-landing.png")
        await m.goto(BASE + "/portfolio.html"); await m.wait_for_timeout(1200)
        await m.click("[data-filter='residential']"); await m.wait_for_timeout(1500)
        await m.evaluate("window.scrollTo(0, document.querySelector('#work').offsetTop - 56)"); await m.wait_for_timeout(1200)
        await m.screenshot(path=f"{OUT}/13-mobile-residential.png")
        await m.click(".card__btn"); await m.wait_for_timeout(1500)
        await m.screenshot(path=f"{OUT}/14-mobile-folder-detail.png")
        await m.keyboard.press("Escape"); await m.wait_for_timeout(600)
        await m.click("[data-filter='public']"); await m.wait_for_timeout(1500)
        await m.screenshot(path=f"{OUT}/15-mobile-empty-category.png")
        await m.evaluate("window.scrollTo(0, document.body.scrollHeight)"); await m.wait_for_timeout(1000)
        await m.screenshot(path=f"{OUT}/16-mobile-contact.png")
        print("errors:", errs)
        await b.close()
asyncio.run(main())
